/**
 * Generates the font metrics that invitation designs are laid out with,
 * and the map from each face to its files.
 *
 *   pnpm --filter web exec tsx scripts/gen-design-fonts.ts
 *
 * Run it after changing FONTS in packages/design/src/fonts.ts. The metrics
 * are what let the server, the browser and the PDF break a line in the
 * same place without asking a browser to measure anything: advances for
 * the characters the latin subset covers, and the pair kerning between
 * them, read from the very files the page and the PDF use.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import fontkit from "@pdf-lib/fontkit";
import {
	FACES,
	type FontId,
	parseFace,
} from "../../../packages/design/src/fonts";

const here = dirname(fileURLToPath(import.meta.url));
const web = join(here, "..");
const metricsDir = join(web, "../../packages/design/src/metrics");

/** The characters a design can print: what the latin subset holds. */
const CHARS = [
	...range(0x20, 0x7e),
	...range(0xa0, 0xff),
	0x2013,
	0x2014,
	0x2018,
	0x2019,
	0x201c,
	0x201d,
	0x2022,
	0x2026,
	0x20ac,
	0x2122,
].map((c) => String.fromCodePoint(c));

/**
 * Kerning is read between these only. An accented letter kerns as its base
 * letter (text.ts strips the accent before the lookup), which keeps the
 * tables small enough to ship to the server: most of a font's latin-1
 * pairs are its ASCII classes repeated.
 */
const KERNED = [...range(0x21, 0x7e), 0x2018, 0x2019, 0x201c, 0x201d].map((c) =>
	String.fromCodePoint(c),
);

/** Kerning smaller than this (in thousandths of an em) is left out. */
const KERN_FLOOR = 5;

function range(a: number, b: number): number[] {
	return Array.from({ length: b - a + 1 }, (_, i) => a + i);
}

function fileOf(
	id: FontId,
	weight: number,
	italic: boolean,
	ext: "woff" | "woff2",
): string {
	return `@fontsource/${id}/files/${id}-latin-${weight}-${italic ? "italic" : "normal"}.${ext}`;
}

const index: string[] = [];
const urls: string[] = [];
const imports: string[] = [];

for (const face of FACES) {
	const { font: id, weight, italic } = parseFace(face);
	const path = join(web, "node_modules", fileOf(id, weight, italic, "woff"));
	const font = fontkit.create(readFileSync(path));
	const upm = font.unitsPerEm;
	const k = 1000 / upm;

	const chars = CHARS.filter((c) =>
		font.hasGlyphForCodePoint(c.codePointAt(0) ?? 0),
	);
	const adv = chars.map((c) =>
		Math.round(font.glyphForCodePoint(c.codePointAt(0) ?? 0).advanceWidth * k),
	);
	const kerned = KERNED.filter((c) => chars.includes(c));
	const kern: string[] = [];
	for (const a of kerned) {
		const base = font.glyphForCodePoint(a.codePointAt(0) ?? 0).advanceWidth;
		for (const b of kerned) {
			const run = font.layout(a + b, {
				liga: false,
				calt: false,
				clig: false,
				dlig: false,
			});
			if (run.glyphs.length !== 2) continue;
			const pos = run.positions[0];
			if (!pos) continue;
			const d = Math.round((pos.xAdvance - base) * k);
			if (Math.abs(d) >= KERN_FLOOR) kern.push(`${a}${b}${d}`);
		}
	}
	const metrics = {
		asc: Math.round(font.ascent * k),
		desc: Math.round(font.descent * k),
		chars: chars.join(""),
		adv,
		// "<a><b><adjust>" joined by spaces; text.ts parses it once.
		kern: kern.join(" "),
	};
	writeFileSync(
		join(metricsDir, `${face}.ts`),
		`// Generated by apps/web/scripts/gen-design-fonts.ts. Do not edit.\nimport type { FaceMetrics } from "../text";\n\nconst metrics: FaceMetrics = ${JSON.stringify(metrics)};\n\nexport default metrics;\n`,
	);
	index.push(`\t"${face}": () => import("./${face}"),`);
	const v = face.replace(/-/g, "_");
	imports.push(
		`import ${v}_woff2 from "${fileOf(id, weight, italic, "woff2")}?url";`,
		`import ${v}_woff from "${fileOf(id, weight, italic, "woff")}?url";`,
	);
	urls.push(`\t"${face}": { woff2: ${v}_woff2, woff: ${v}_woff },`);
	console.log(face, chars.length, "chars,", kern.length, "pairs");
}

writeFileSync(
	join(metricsDir, "index.ts"),
	`// Generated by apps/web/scripts/gen-design-fonts.ts. Do not edit.\nimport type { FaceKey } from "../fonts";\nimport type { FaceMetrics } from "../text";\n\nexport const METRICS: Record<FaceKey, () => Promise<{ default: FaceMetrics }>> = {\n${index.join("\n")}\n};\n`,
);
writeFileSync(
	join(web, "src/lib/design-fonts.gen.ts"),
	`// Generated by scripts/gen-design-fonts.ts. Do not edit.\n// woff2 for the browser, woff for the PDF (fontkit reads either; the\n// browser prefers the smaller one).\nimport type { FaceKey } from "@rsvp-site/design/fonts";\n${imports.join("\n")}\n\nexport const FONT_FILES: Record<FaceKey, { woff2: string; woff: string }> = {\n${urls.join("\n")}\n};\n`,
);

/**
 * The sticker set: Phosphor's "fill" icons (MIT), one path each on a 256
 * box, so pdf-lib's drawSvgPath, a canvas Path2D and an SVG <path> all
 * fill the same outline.
 */
const STICKERS = [
	"balloon",
	"cake",
	"confetti",
	"gift",
	"star",
	"star-four",
	"sparkle",
	"shooting-star",
	"heart",
	"heart-straight",
	"flower",
	"flower-lotus",
	"flower-tulip",
	"leaf",
	"clover",
	"butterfly",
	"bird",
	"champagne",
	"wine",
	"martini",
	"beer-stein",
	"coffee",
	"music-notes",
	"disco-ball",
	"microphone-stage",
	"guitar",
	"sun",
	"moon",
	"cloud",
	"rainbow",
	"snowflake",
	"tree-evergreen",
	"fire",
	"crown",
	"diamond",
	"pizza",
	"ice-cream",
	"cookie",
	"baby",
	"ghost",
	"paw-print",
	"cat",
	"dog",
	"egg",
	"rabbit",
	"church",
	"bell",
	"house-line",
	"map-pin",
	"calendar-star",
	"camera",
	"smiley",
];
/**
 * Art-deco frame pieces, drawn here rather than taken from an icon set:
 * one corner of a stepped double-line frame with a diamond, and its third
 * line on its own (it is a different colour in the template that uses
 * it). Strokes are outlined as polygons all wound the same way, so the
 * nonzero fill every renderer uses unions them, and the diamond rings wind
 * their holes the other way. A corner turned 90, 180 and 270 degrees makes
 * the other three.
 */
function decoCorner(part: "frame" | "line"): string {
	const box = 400;
	const k = 256 / box;
	const half = 1.1; // half a stroke, in the 400-unit corner
	const [o, m, i, end] = [28, 44, 60, box];
	type P = [number, number];
	const quad = (a: P, b: P): P[] => {
		const len = Math.hypot(b[0] - a[0], b[1] - a[1]);
		const ux = (b[0] - a[0]) / len;
		const uy = (b[1] - a[1]) / len;
		const nx = -uy * half;
		const ny = ux * half;
		const a2: P = [a[0] - ux * half, a[1] - uy * half];
		const b2: P = [b[0] + ux * half, b[1] + uy * half];
		return [
			[a2[0] + nx, a2[1] + ny],
			[b2[0] + nx, b2[1] + ny],
			[b2[0] - nx, b2[1] - ny],
			[a2[0] - nx, a2[1] - ny],
		];
	};
	const area = (p: P[]) =>
		p.reduce((s, q, j) => {
			const r = p[(j + 1) % p.length] as P;
			return s + q[0] * r[1] - r[0] * q[1];
		}, 0);
	const wind = (p: P[], positive: boolean) =>
		area(p) > 0 === positive ? p : [...p].reverse();
	const diamond = (r: number): P[] => [
		[80, 80 - r],
		[80 + r, 80],
		[80, 80 + r],
		[80 - r, 80],
	];
	const mirror = ([a, b]: [P, P]): [P, P] => [
		[a[1], a[0]],
		[b[1], b[0]],
	];
	const top: [P, P][] =
		part === "line"
			? [
					[
						[152, m],
						[end, m],
					],
				]
			: [
					[
						[164, o],
						[end, o],
					],
					[
						[164, o],
						[134, i],
					],
					[
						[97.5, i],
						[134, i],
					],
					[
						[190, i],
						[end, i],
					],
				];
	const polys: P[][] = [...top, ...top.map(mirror)].map(([a, b]) =>
		wind(quad(a, b), true),
	);
	if (part === "frame") {
		const d = half * Math.SQRT2;
		for (const r of [37.5, 23]) {
			polys.push(wind(diamond(r + d), true), wind(diamond(r - d), false));
		}
	}
	const f = (n: number) => Math.round(n * k * 100) / 100;
	return polys
		.map((p) => `M${p.map(([x, y]) => `${f(x)},${f(y)}`).join(" L")} Z`)
		.join(" ");
}

const stickerLines = STICKERS.map((name) => {
	const svg = readFileSync(
		join(
			web,
			"node_modules/@phosphor-icons/core/assets/fill",
			`${name}-fill.svg`,
		),
		"utf8",
	);
	const paths = [...svg.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]);
	if (paths.length !== 1) throw new Error(`${name}: ${paths.length} paths`);
	return `\t"${name}": "${paths[0]}",`;
});
stickerLines.push(
	`\t"deco-corner": "${decoCorner("frame")}",`,
	`\t"deco-corner-line": "${decoCorner("line")}",`,
);
writeFileSync(
	join(metricsDir, "../stickers.ts"),
	`// Generated by apps/web/scripts/gen-design-fonts.ts from @phosphor-icons/core\n// (MIT, Copyright (c) 2023 Phosphor Icons), and the deco frame pieces drawn
// by that script. Do not edit.\n\n/** Each sticker is one filled path on a 256x256 box. */\nexport const STICKERS = {\n${stickerLines.join("\n")}\n} as const;\n\nexport type StickerId = keyof typeof STICKERS;\n\nexport const STICKER_IDS = Object.keys(STICKERS) as [StickerId, ...StickerId[]];\n`,
);
