import type { ElementInput } from "../schema";
import { coverImage, qrBlock } from "./parts";
import type { Template } from "./types";

const INK = "#2a2140";
const PINK = "#ff5c8a";
const SUN = "#ffcf33";
const SKY = "#3fb6ff";

/** A square of confetti with a white panel, balloons and a round, happy face. */
export const confetti: Template = {
	id: "confetti",
	label: "Confetti birthday",
	build: ({ cover, paper }) => {
		const art: ElementInput[] = cover
			? [
					coverImage(
						cover,
						{ x: 380, y: 110, w: 240, h: 240 },
						{ mask: "circle", border: { color: SUN, width: 12 } },
					),
				]
			: [
					{
						id: "b1",
						type: "sticker",
						x: 330,
						y: 110,
						w: 150,
						h: 220,
						sticker: "balloon",
						color: PINK,
						rot: -12,
					},
					{
						id: "b2",
						type: "sticker",
						x: 430,
						y: 90,
						w: 150,
						h: 220,
						sticker: "balloon",
						color: SKY,
						rot: 4,
					},
					{
						id: "b3",
						type: "sticker",
						x: 530,
						y: 115,
						w: 150,
						h: 220,
						sticker: "balloon",
						color: SUN,
						rot: 14,
					},
				];
		return {
			v: 1,
			format: "square",
			background: {
				kind: "pattern",
				pattern: "confetti",
				color: "#fff8e7",
				colors: [PINK, SUN, SKY, "#7ed957"],
				scale: 1,
				seed: 9,
			},
			theme: {
				bg: "#fff8e7",
				panel: "#ffffff",
				text: INK,
				accent: SUN,
				accent2: PINK,
				headingFont: "fredoka",
				bodyFont: "fredoka",
			},
			elements: [
				{
					id: "panel",
					type: "rect",
					x: 80,
					y: 80,
					w: 840,
					h: 840,
					radius: 60,
					fill: "#ffffff",
					opacity: 0.94,
				},
				...art,
				{
					id: "intro",
					type: "text",
					x: 120,
					y: 360,
					w: 760,
					h: 50,
					text: "Come party with us!",
					font: "fredoka",
					weight: 600,
					size: 40,
					align: "center",
					color: PINK,
				},
				{
					id: "title",
					type: "text",
					x: 120,
					y: 410,
					w: 760,
					h: 200,
					text: "{title}",
					font: "fredoka",
					weight: 600,
					size: 92,
					lineHeight: 1,
					align: "center",
					valign: "middle",
					fit: "shrink",
					color: INK,
				},
				{
					id: "when",
					type: "text",
					x: paper ? 130 : 120,
					y: 630,
					w: paper ? 520 : 760,
					h: 90,
					text: "{date} · {time}",
					font: "fredoka",
					weight: 600,
					size: 34,
					lineHeight: 1.25,
					align: paper ? "left" : "center",
					color: INK,
				},
				{
					id: "where",
					type: "text",
					x: paper ? 130 : 120,
					y: 722,
					w: paper ? 520 : 760,
					h: 44,
					text: "{location}",
					font: "fredoka",
					weight: 400,
					size: 30,
					fit: "shrink",
					align: paper ? "left" : "center",
					color: INK,
				},
				{
					id: "details",
					type: "text",
					x: paper ? 130 : 120,
					y: 770,
					w: paper ? 520 : 760,
					h: 76,
					text: "{details}",
					font: "fredoka",
					weight: 400,
					size: 24,
					lineHeight: 1.3,
					align: paper ? "left" : "center",
					fit: "shrink",
					color: INK,
				},
				{
					id: "rsvp",
					type: "text",
					x: paper ? 130 : 120,
					y: 852,
					w: paper ? 520 : 760,
					h: 40,
					text: "RSVP by {rsvp by}",
					font: "fredoka",
					weight: 600,
					size: 28,
					align: paper ? "left" : "center",
					color: PINK,
				},
				...qrBlock(
					paper,
					{ x: 680, y: 620, size: 200 },
					{ font: "fredoka", color: PINK },
				),
			],
		};
	},
};
