import type { ElementInput } from "../schema";
import { coverImage, qrBlock } from "./parts";
import type { Template } from "./types";

const INK = "#2f3a2f";
const SAGE = "#7a9a6b";
const CLAY = "#b5654d";

/** Cream card, a fine double frame, sage sprigs, a serif that means it. */
export const garden: Template = {
	id: "garden",
	label: "Garden party",
	build: ({ cover, paper }) => {
		const photo: ElementInput[] = cover
			? [
					coverImage(
						cover,
						{ x: 360, y: 130, w: 280, h: 280 },
						{ mask: "circle", border: { color: SAGE, width: 10 } },
					),
				]
			: [
					{
						id: "sprig1",
						type: "sticker",
						x: 380,
						y: 200,
						w: 120,
						h: 120,
						sticker: "leaf",
						color: SAGE,
						rot: -30,
					},
					{
						id: "sprig2",
						type: "sticker",
						x: 500,
						y: 200,
						w: 120,
						h: 120,
						sticker: "flower-tulip",
						color: CLAY,
						rot: 15,
					},
				];
		const top = cover ? 450 : 380;
		return {
			v: 1,
			format: "5x7",
			background: { kind: "solid", color: "#fbf6ee" },
			theme: {
				bg: "#f4efe6",
				panel: "#ffffff",
				text: INK,
				accent: SAGE,
				accent2: CLAY,
				headingFont: "playfair-display",
				bodyFont: "lora",
			},
			elements: [
				{
					id: "frame1",
					type: "rect",
					x: 50,
					y: 50,
					w: 900,
					h: 1300,
					stroke: SAGE,
					strokeWidth: 4,
				},
				{
					id: "frame2",
					type: "rect",
					x: 70,
					y: 70,
					w: 860,
					h: 1260,
					stroke: SAGE,
					strokeWidth: 1.5,
				},
				...photo,
				{
					id: "intro",
					type: "text",
					x: 150,
					y: top,
					w: 700,
					h: 50,
					text: "You are warmly invited to",
					font: "cormorant-garamond",
					weight: 400,
					size: 40,
					align: "center",
					color: INK,
				},
				{
					id: "title",
					type: "text",
					x: 120,
					y: top + 60,
					w: 760,
					h: 250,
					text: "{title}",
					font: "playfair-display",
					weight: 700,
					size: 96,
					lineHeight: 1.05,
					align: "center",
					valign: "middle",
					fit: "shrink",
					color: INK,
				},
				{
					id: "rule",
					type: "line",
					x: 400,
					y: top + 320,
					w: 200,
					h: 10,
					stroke: CLAY,
					strokeWidth: 3,
				},
				{
					id: "when",
					type: "text",
					x: 150,
					y: top + 360,
					w: 700,
					h: 100,
					text: "{date}\n{time}",
					font: "lora",
					weight: 700,
					size: 36,
					lineHeight: 1.3,
					align: "center",
					color: INK,
				},
				{
					id: "where",
					type: "text",
					x: 150,
					y: top + 470,
					w: 700,
					h: 90,
					text: "{location}",
					font: "lora",
					weight: 400,
					size: 32,
					align: "center",
					color: INK,
				},
				{
					id: "details",
					type: "text",
					x: paper ? 110 : 150,
					y: top + 565,
					w: paper ? 560 : 700,
					h: (paper ? 1160 : 1170) - (top + 565),
					text: "{details}",
					font: "lora",
					weight: 400,
					size: 28,
					lineHeight: 1.35,
					align: paper ? "left" : "center",
					fit: "shrink",
					color: INK,
				},
				{
					id: "host",
					type: "text",
					x: paper ? 110 : 150,
					y: paper ? 1170 : 1180,
					w: paper ? 500 : 700,
					h: 50,
					text: "Hosted by {host}",
					font: "cormorant-garamond",
					weight: 700,
					size: 34,
					align: paper ? "left" : "center",
					color: SAGE,
				},
				{
					id: "rsvp",
					type: "text",
					x: paper ? 110 : 150,
					y: paper ? 1225 : 1235,
					w: paper ? 500 : 700,
					h: 44,
					text: "Kindly reply by {rsvp by}",
					font: "lora",
					weight: 400,
					size: 28,
					align: paper ? "left" : "center",
					color: CLAY,
				},
				...qrBlock(
					paper,
					{ x: 690, y: 1050, size: 200 },
					{ font: "lora", color: CLAY },
				),
			],
		};
	},
};
