// Generated by scripts/gen-design-fonts.ts. Do not edit.
// woff2 for the browser, woff for the PDF (fontkit reads either; the
// browser prefers the smaller one).

import abril_fatface_400_woff from "@fontsource/abril-fatface/files/abril-fatface-latin-400-normal.woff?url";
import abril_fatface_400_woff2 from "@fontsource/abril-fatface/files/abril-fatface-latin-400-normal.woff2?url";
import anton_400_woff from "@fontsource/anton/files/anton-latin-400-normal.woff?url";
import anton_400_woff2 from "@fontsource/anton/files/anton-latin-400-normal.woff2?url";
import archivo_black_400_woff from "@fontsource/archivo-black/files/archivo-black-latin-400-normal.woff?url";
import archivo_black_400_woff2 from "@fontsource/archivo-black/files/archivo-black-latin-400-normal.woff2?url";
import baloo_2_500_woff from "@fontsource/baloo-2/files/baloo-2-latin-500-normal.woff?url";
import baloo_2_500_woff2 from "@fontsource/baloo-2/files/baloo-2-latin-500-normal.woff2?url";
import baloo_2_800_woff from "@fontsource/baloo-2/files/baloo-2-latin-800-normal.woff?url";
import baloo_2_800_woff2 from "@fontsource/baloo-2/files/baloo-2-latin-800-normal.woff2?url";
import bebas_neue_400_woff from "@fontsource/bebas-neue/files/bebas-neue-latin-400-normal.woff?url";
import bebas_neue_400_woff2 from "@fontsource/bebas-neue/files/bebas-neue-latin-400-normal.woff2?url";
import caveat_400_woff from "@fontsource/caveat/files/caveat-latin-400-normal.woff?url";
import caveat_400_woff2 from "@fontsource/caveat/files/caveat-latin-400-normal.woff2?url";
import caveat_700_woff from "@fontsource/caveat/files/caveat-latin-700-normal.woff?url";
import caveat_700_woff2 from "@fontsource/caveat/files/caveat-latin-700-normal.woff2?url";
import cormorant_garamond_400_woff from "@fontsource/cormorant-garamond/files/cormorant-garamond-latin-400-normal.woff?url";
import cormorant_garamond_400_woff2 from "@fontsource/cormorant-garamond/files/cormorant-garamond-latin-400-normal.woff2?url";
import cormorant_garamond_700_woff from "@fontsource/cormorant-garamond/files/cormorant-garamond-latin-700-normal.woff?url";
import cormorant_garamond_700_woff2 from "@fontsource/cormorant-garamond/files/cormorant-garamond-latin-700-normal.woff2?url";
import dancing_script_400_woff from "@fontsource/dancing-script/files/dancing-script-latin-400-normal.woff?url";
import dancing_script_400_woff2 from "@fontsource/dancing-script/files/dancing-script-latin-400-normal.woff2?url";
import dancing_script_700_woff from "@fontsource/dancing-script/files/dancing-script-latin-700-normal.woff?url";
import dancing_script_700_woff2 from "@fontsource/dancing-script/files/dancing-script-latin-700-normal.woff2?url";
import dm_serif_display_400_woff from "@fontsource/dm-serif-display/files/dm-serif-display-latin-400-normal.woff?url";
import dm_serif_display_400_woff2 from "@fontsource/dm-serif-display/files/dm-serif-display-latin-400-normal.woff2?url";
import fraunces_400_woff from "@fontsource/fraunces/files/fraunces-latin-400-normal.woff?url";
import fraunces_400_woff2 from "@fontsource/fraunces/files/fraunces-latin-400-normal.woff2?url";
import fraunces_700_woff from "@fontsource/fraunces/files/fraunces-latin-700-normal.woff?url";
import fraunces_700_woff2 from "@fontsource/fraunces/files/fraunces-latin-700-normal.woff2?url";
import fraunces_900_woff from "@fontsource/fraunces/files/fraunces-latin-900-normal.woff?url";
import fraunces_900_woff2 from "@fontsource/fraunces/files/fraunces-latin-900-normal.woff2?url";
import fredoka_400_woff from "@fontsource/fredoka/files/fredoka-latin-400-normal.woff?url";
import fredoka_400_woff2 from "@fontsource/fredoka/files/fredoka-latin-400-normal.woff2?url";
import fredoka_600_woff from "@fontsource/fredoka/files/fredoka-latin-600-normal.woff?url";
import fredoka_600_woff2 from "@fontsource/fredoka/files/fredoka-latin-600-normal.woff2?url";
import lora_400_woff from "@fontsource/lora/files/lora-latin-400-normal.woff?url";
import lora_400_woff2 from "@fontsource/lora/files/lora-latin-400-normal.woff2?url";
import lora_700_woff from "@fontsource/lora/files/lora-latin-700-normal.woff?url";
import lora_700_woff2 from "@fontsource/lora/files/lora-latin-700-normal.woff2?url";
import manrope_400_woff from "@fontsource/manrope/files/manrope-latin-400-normal.woff?url";
import manrope_400_woff2 from "@fontsource/manrope/files/manrope-latin-400-normal.woff2?url";
import manrope_600_woff from "@fontsource/manrope/files/manrope-latin-600-normal.woff?url";
import manrope_600_woff2 from "@fontsource/manrope/files/manrope-latin-600-normal.woff2?url";
import manrope_800_woff from "@fontsource/manrope/files/manrope-latin-800-normal.woff?url";
import manrope_800_woff2 from "@fontsource/manrope/files/manrope-latin-800-normal.woff2?url";
import pacifico_400_woff from "@fontsource/pacifico/files/pacifico-latin-400-normal.woff?url";
import pacifico_400_woff2 from "@fontsource/pacifico/files/pacifico-latin-400-normal.woff2?url";
import permanent_marker_400_woff from "@fontsource/permanent-marker/files/permanent-marker-latin-400-normal.woff?url";
import permanent_marker_400_woff2 from "@fontsource/permanent-marker/files/permanent-marker-latin-400-normal.woff2?url";
import playfair_display_400_woff from "@fontsource/playfair-display/files/playfair-display-latin-400-normal.woff?url";
import playfair_display_400_woff2 from "@fontsource/playfair-display/files/playfair-display-latin-400-normal.woff2?url";
import playfair_display_700_woff from "@fontsource/playfair-display/files/playfair-display-latin-700-normal.woff?url";
import playfair_display_700_woff2 from "@fontsource/playfair-display/files/playfair-display-latin-700-normal.woff2?url";
import playfair_display_900_woff from "@fontsource/playfair-display/files/playfair-display-latin-900-normal.woff?url";
import playfair_display_900_woff2 from "@fontsource/playfair-display/files/playfair-display-latin-900-normal.woff2?url";
import poppins_400_woff from "@fontsource/poppins/files/poppins-latin-400-normal.woff?url";
import poppins_400_woff2 from "@fontsource/poppins/files/poppins-latin-400-normal.woff2?url";
import poppins_600_woff from "@fontsource/poppins/files/poppins-latin-600-normal.woff?url";
import poppins_600_woff2 from "@fontsource/poppins/files/poppins-latin-600-normal.woff2?url";
import poppins_800_woff from "@fontsource/poppins/files/poppins-latin-800-normal.woff?url";
import poppins_800_woff2 from "@fontsource/poppins/files/poppins-latin-800-normal.woff2?url";
import righteous_400_woff from "@fontsource/righteous/files/righteous-latin-400-normal.woff?url";
import righteous_400_woff2 from "@fontsource/righteous/files/righteous-latin-400-normal.woff2?url";
import shrikhand_400_woff from "@fontsource/shrikhand/files/shrikhand-latin-400-normal.woff?url";
import shrikhand_400_woff2 from "@fontsource/shrikhand/files/shrikhand-latin-400-normal.woff2?url";
import space_grotesk_400_woff from "@fontsource/space-grotesk/files/space-grotesk-latin-400-normal.woff?url";
import space_grotesk_400_woff2 from "@fontsource/space-grotesk/files/space-grotesk-latin-400-normal.woff2?url";
import space_grotesk_700_woff from "@fontsource/space-grotesk/files/space-grotesk-latin-700-normal.woff?url";
import space_grotesk_700_woff2 from "@fontsource/space-grotesk/files/space-grotesk-latin-700-normal.woff2?url";
import unbounded_400_woff from "@fontsource/unbounded/files/unbounded-latin-400-normal.woff?url";
import unbounded_400_woff2 from "@fontsource/unbounded/files/unbounded-latin-400-normal.woff2?url";
import unbounded_700_woff from "@fontsource/unbounded/files/unbounded-latin-700-normal.woff?url";
import unbounded_700_woff2 from "@fontsource/unbounded/files/unbounded-latin-700-normal.woff2?url";
import unbounded_900_woff from "@fontsource/unbounded/files/unbounded-latin-900-normal.woff?url";
import unbounded_900_woff2 from "@fontsource/unbounded/files/unbounded-latin-900-normal.woff2?url";
import type { FaceKey } from "@rsvp-site/design/fonts";

export const FONT_FILES: Record<FaceKey, { woff2: string; woff: string }> = {
	"unbounded-400": { woff2: unbounded_400_woff2, woff: unbounded_400_woff },
	"unbounded-700": { woff2: unbounded_700_woff2, woff: unbounded_700_woff },
	"unbounded-900": { woff2: unbounded_900_woff2, woff: unbounded_900_woff },
	"manrope-400": { woff2: manrope_400_woff2, woff: manrope_400_woff },
	"manrope-600": { woff2: manrope_600_woff2, woff: manrope_600_woff },
	"manrope-800": { woff2: manrope_800_woff2, woff: manrope_800_woff },
	"fraunces-400": { woff2: fraunces_400_woff2, woff: fraunces_400_woff },
	"fraunces-700": { woff2: fraunces_700_woff2, woff: fraunces_700_woff },
	"fraunces-900": { woff2: fraunces_900_woff2, woff: fraunces_900_woff },
	"playfair-display-400": {
		woff2: playfair_display_400_woff2,
		woff: playfair_display_400_woff,
	},
	"playfair-display-700": {
		woff2: playfair_display_700_woff2,
		woff: playfair_display_700_woff,
	},
	"playfair-display-900": {
		woff2: playfair_display_900_woff2,
		woff: playfair_display_900_woff,
	},
	"dm-serif-display-400": {
		woff2: dm_serif_display_400_woff2,
		woff: dm_serif_display_400_woff,
	},
	"lora-400": { woff2: lora_400_woff2, woff: lora_400_woff },
	"lora-700": { woff2: lora_700_woff2, woff: lora_700_woff },
	"cormorant-garamond-400": {
		woff2: cormorant_garamond_400_woff2,
		woff: cormorant_garamond_400_woff,
	},
	"cormorant-garamond-700": {
		woff2: cormorant_garamond_700_woff2,
		woff: cormorant_garamond_700_woff,
	},
	"abril-fatface-400": {
		woff2: abril_fatface_400_woff2,
		woff: abril_fatface_400_woff,
	},
	"bebas-neue-400": { woff2: bebas_neue_400_woff2, woff: bebas_neue_400_woff },
	"anton-400": { woff2: anton_400_woff2, woff: anton_400_woff },
	"archivo-black-400": {
		woff2: archivo_black_400_woff2,
		woff: archivo_black_400_woff,
	},
	"space-grotesk-400": {
		woff2: space_grotesk_400_woff2,
		woff: space_grotesk_400_woff,
	},
	"space-grotesk-700": {
		woff2: space_grotesk_700_woff2,
		woff: space_grotesk_700_woff,
	},
	"poppins-400": { woff2: poppins_400_woff2, woff: poppins_400_woff },
	"poppins-600": { woff2: poppins_600_woff2, woff: poppins_600_woff },
	"poppins-800": { woff2: poppins_800_woff2, woff: poppins_800_woff },
	"fredoka-400": { woff2: fredoka_400_woff2, woff: fredoka_400_woff },
	"fredoka-600": { woff2: fredoka_600_woff2, woff: fredoka_600_woff },
	"baloo-2-500": { woff2: baloo_2_500_woff2, woff: baloo_2_500_woff },
	"baloo-2-800": { woff2: baloo_2_800_woff2, woff: baloo_2_800_woff },
	"pacifico-400": { woff2: pacifico_400_woff2, woff: pacifico_400_woff },
	"shrikhand-400": { woff2: shrikhand_400_woff2, woff: shrikhand_400_woff },
	"righteous-400": { woff2: righteous_400_woff2, woff: righteous_400_woff },
	"caveat-400": { woff2: caveat_400_woff2, woff: caveat_400_woff },
	"caveat-700": { woff2: caveat_700_woff2, woff: caveat_700_woff },
	"permanent-marker-400": {
		woff2: permanent_marker_400_woff2,
		woff: permanent_marker_400_woff,
	},
	"dancing-script-400": {
		woff2: dancing_script_400_woff2,
		woff: dancing_script_400_woff,
	},
	"dancing-script-700": {
		woff2: dancing_script_700_woff2,
		woff: dancing_script_700_woff,
	},
};
